### ISSUE TITLE
Symlink unter Windows 10, npm version 5.8.0

### ISSUE THREAD

**Issue by ArneOb** [schul-cloud/edtrio#14]
> x@0.1.0 postinstall C:\programm\nodejs_edtrio
> node scripts/symlink_source.js

C:\programm\nodejs_edtrio\scripts\symlink_source.js:8
    mklink /d "C:\programm\nodejs_edtrio\src" "C:\programm\nodejs_edtrio\node_modules\x-editor"
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! x@0.1.0 postinstall: `node scripts/symlink_source.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the x@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
------------------------
Vorschläge für Workaround (da das eigentlich keine wichtige Stelle ist, oder?)

**Comment by ArneOb** [comment]
Der Ordner src soll als ein quasi Node Module gelten, richtig? Oder gibt es noch andere Gründe?
Frage, weil ich dann herausbekommen kann, wie das anders geht.
